import type { Metadata } from "next";
import { Tenor_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const tenorSans = Tenor_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap"
});

export const metadata: Metadata = {
  title: "IKON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tenorSans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
