import type { Metadata } from "next";
import { Tenor_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/footer";
import AntiCopy from "./AntiCopy";

const tenorSans = Tenor_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "IKON",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${tenorSans.className} antialiased`}>
        <AntiCopy />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
