// app/layout.tsx
import type { Metadata } from "next";
import { Tenor_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/footer";
import { useEffect } from "react";

const tenorSans = Tenor_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "IKON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    // Prevent right-click
    const handleContextMenu = (e: MouseEvent) => e.preventDefault();
    document.addEventListener("contextmenu", handleContextMenu);

    // Prevent long press on mobile
    let touchTimer: NodeJS.Timeout;
    const handleTouchStart = (e: TouchEvent) => {
      touchTimer = setTimeout(() => e.preventDefault(), 500);
    };
    const handleTouchEnd = () => clearTimeout(touchTimer);

    document.addEventListener("touchstart", handleTouchStart);
    document.addEventListener("touchend", handleTouchEnd);

    // Prevent copy/cut/paste
    const blockEvent = (e: Event) => e.preventDefault();
    ["copy", "cut", "paste"].forEach(evt =>
      document.addEventListener(evt, blockEvent)
    );

    return () => {
      document.removeEventListener("contextmenu", handleContextMenu);
      document.removeEventListener("touchstart", handleTouchStart);
      document.removeEventListener("touchend", handleTouchEnd);
      ["copy", "cut", "paste"].forEach(evt =>
        document.removeEventListener(evt, blockEvent)
      );
    };
  }, []);

  return (
    <html lang="en">
      <body className={`${tenorSans.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
